### ISSUE TITLE
Doesn't work with current arangojs

### ISSUE THREAD

**Issue by me89** [AlexanderArvidsson/connect-arango#4]
Just tested your framework, it seems to not support the current arangojs API anymore.

**Comment by AlexanderArvidsson** [comment]
I have not maintained this package for years since I no longer use ArangoDB, but you are free to contribute and do a pull request if you want to update it to the current API!

**Comment by me89** [comment]
Actually, it still works, sorry for that. You just need to add in your documentation, that you are required to provide the readyCallback function while creating the store:


```
...
store:  new arangoStore({
        db:         database.name,
        collection: database.prefix +database.collections.session,
        username:   database.user,
        password:   database.password,
        url:        database.url
    }, (cb)=>{
        console.log(cb);
    })
```

**Comment by AlexanderArvidsson** [comment]
Cool! I will do that, thanks for finding that out!
